# Generated by Django 5.0.6 on 2024-06-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=150, verbose_name='Informatsiya')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biz',
                'verbose_name_plural': 'Bizlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Co_workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Hamkorlar')),
                ('comission', models.PositiveIntegerField(default=10, verbose_name='Komissiya')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Komentariya',
                'verbose_name_plural': 'Komentariyalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
            ],
            options={
                'verbose_name': "Qo'shilish",
                'verbose_name_plural': "Qo'shilishlar",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_cards', models.TextField(verbose_name='Plastik Karta')),
                ('credit_cards', models.TextField(verbose_name='Kredit Karta')),
                ('contribution', models.TextField(verbose_name='Hissa')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Tovarlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Job_Openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Kategoriya Xaqida')),
                ('openings', models.CharField(max_length=50, verbose_name='Vakansiya')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings_comment', to='creditapp.comment')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Be_Co_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_worker', to='creditapp.joining')),
            ],
            options={
                'verbose_name': 'Hohlash',
                'verbose_name_plural': 'Hohlashlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LegalEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_entities', to='creditapp.about_us')),
                ('be_co_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_entities', to='creditapp.be_co_worker')),
                ('joining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_entities', to='creditapp.joining')),
            ],
            options={
                'verbose_name': 'Yurid. Li.',
                'verbose_name_plural': 'Yurid. Li.',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=175, verbose_name='Informatsiya')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_comment', to='creditapp.comment')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender', models.CharField(max_length=75, verbose_name='Tender')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_comment', to='creditapp.comment')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenderlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_workers', to='creditapp.co_workers')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_comment', to='creditapp.comment')),
            ],
            options={
                'verbose_name': 'Perevod',
                'verbose_name_plural': 'Perevodlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_individual', to='creditapp.co_workers')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_comment', to='creditapp.comment')),
                ('job_Openings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_individual', to='creditapp.job_openings')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_individual', to='creditapp.products')),
                ('tariffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_individual', to='creditapp.tariffs')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_individual', to='creditapp.tender')),
                ('transfers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_individual', to='creditapp.transfers')),
            ],
            options={
                'verbose_name': 'Fiz. Li.',
                'verbose_name_plural': 'Fiz. Li.',
                'ordering': ('-created_at',),
            },
        ),
    ]
